# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/deepin-image-viewer.spec

# add or remove files that should be synced
synced_files:
    - rpm/deepin-image-viewer.spec
    - .packit.yaml

upstream_package_name: deepin-image-viewer
# downstream (Fedora) RPM package name
downstream_package_name: deepin-image-viewer

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/deepin-image-viewer.spec"
