/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DIVDBusController -p divdbuscontroller imageviewer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DIVDBUSCONTROLLER_H
#define DIVDBUSCONTROLLER_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.deepin.deepinimageviewer
 */
class DIVDBusController: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticServiceName()
    { return "com.deepin.deepinimageviewer"; }
    static inline const char *staticInterfacePath()
    { return "/com/deepin/deepinimageviewer"; }
    static inline const char *staticInterfaceName()
    { return "com.deepin.deepinimageviewer"; }

public:
    DIVDBusController(QObject *parent = 0);

    ~DIVDBusController();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> backToMainWindow()
    {
        return asyncCall(QStringLiteral("backToMainWindow"));
    }

    inline QDBusPendingReply<> editImage(const QString &path)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(path);
        return asyncCallWithArgumentList(QStringLiteral("editImage"), argumentList);
    }

    inline QDBusPendingReply<> enterAlbum(const QString &album)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(album);
        return asyncCallWithArgumentList(QStringLiteral("enterAlbum"), argumentList);
    }

    inline QDBusPendingReply<> searchImage(const QString &keyWord)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(keyWord);
        return asyncCallWithArgumentList(QStringLiteral("searchImage"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace deepin {
    typedef ::DIVDBusController deepinimageviewer;
  }
}
#endif
