/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DIVDBusController -p divdbuscontroller com.deepin.ImageViewer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "divdbuscontroller.h"

/*
 * Implementation of interface class DIVDBusController
 */

DIVDBusController::DIVDBusController(QObject *parent)
    : QDBusAbstractInterface(staticInterfaceService(), staticInterfacePath(),
                             staticInterfaceName(), QDBusConnection::sessionBus(), parent)
{
}

DIVDBusController::~DIVDBusController()
{
}

