.\" This file is processed to generate manpages in the
.\" build diretory.
.TH deepin-image-viewer 1  "2020-11-17" "Deepin"

.SH NAME
deepin-image-viewer \- the picture manager from UOS

.SH SYNOPSIS
.B deepin-image-viewer
[\fIPATH\fR]

.SH DESCRIPTION
Deepin Image Viewer is a fashion photo manager for viewing and organizing pictures.

.PP
This program does not accept any command line options.

If the \fIPATH\fR is specified, open that picture with Image Viewer.
If the \fIPATH\fR is omitted, open Image Viewer and show all pictures in it.
If Image Viewer has been launched, open the picture with Image Viewer. 
Otherwise, launch Image Viewer and open the picture with it.

.SH SEE ALSO
https://www.deepin.org/en/original/deepin-image-viewer/

.SH AUTHOR
.PP
.B deepin-image-viewer
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT liuminghang@\:uniontech.com
Liu Ming Hang
.ME
for the Debian Project (but may be used by others).
